server:
  port: ${PORT:8081}

spring:
  application:
    name: ${APP_NAME:challenges}

    # PostgreSQL
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}?ssl=${DB_SSL_ENABLED:false}&sslmode=${DB_SSL_MODE:require}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASS:rabbitmq}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:false}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-retries: 3

app:
  jwt:
    secret: ${JWT_SECRET:8x/c+pXQ3Q9m+9b2tZ/vT1gQzYqXlO/m+HwA9R5z7J8=}
  challenges:
    internal-token: ${CHALLENGES_INTERNAL_TOKEN:changeme-internal-token}
  messaging:
    challenges:
      exchange: ${CHALLENGES_EXCHANGE:challenges.solutions.exchange}
    solutions:
      routing-keys:
        solution-requested: ${SOLUTIONS_ROUTING_KEY_SOLUTION_REQUESTED:challenges.solution.requested}

# Eureka Config
eureka:
  instance:
    # When using Docker/k8s then true
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /api/v1/${spring.application.name}/actuator
  endpoint:
    health:
      show-details: never
